import 'server-only';
import type { ColumnDef, FieldDef, RelationDef, ResourceDef } from './types';

// ── field helpers ──
const text = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'text', ...o });
const area = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'textarea', ...o });
const num = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'number', min: 0, ...o });
const money = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'money', min: 0, step: 1, ...o });
const date = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'date', ...o });
const time = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'time', ...o });
const check = (name: string, label: string, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'checkbox', ...o });
const sel = (name: string, label: string, options: string[] | [string, string][], o: Partial<FieldDef> = {}): FieldDef => ({
  name, label, type: 'select', options: options.map((x) => (Array.isArray(x) ? { value: x[0], label: x[1] } : { value: x, label: x.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase()) })), ...o });
const rel = (name: string, label: string, relation: RelationDef, o: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'select', relation, ...o });
const col = (key: string, label: string, type: ColumnDef['type'] = 'text', hideOnMobile = false): ColumnDef => ({ key, label, type, hideOnMobile });

// ── common relations ──
const R = {
  year: { table: 'academic_years', label: (r) => r.name, order: 'start_date.desc' } as RelationDef,
  classes: { table: 'classes', select: 'id,name,level', label: (r) => r.name, order: 'level', campusScoped: true } as RelationDef,
  sections: { table: 'sections', select: 'id,name,classes(name)', label: (r) => `${r.classes?.name ?? ''} – ${r.name}`, campusScoped: true } as RelationDef,
  subject: { table: 'subjects', label: (r) => `${r.name} (${r.code})`, order: 'name' } as RelationDef,
  department: { table: 'departments', label: (r) => r.name, order: 'name' } as RelationDef,
  category: { table: 'fee_categories', label: (r) => r.name, order: 'name', eq: { is_active: true } } as RelationDef,
  rooms: { table: 'rooms', label: (r) => r.name, order: 'name', campusScoped: true } as RelationDef,
  staff: { table: 'staff', select: 'id,full_name,employee_code', label: (r) => `${r.full_name} (${r.employee_code})`, order: 'full_name', campusScoped: true, eq: { status: 'active' } } as RelationDef,
  vehicle: { table: 'vehicles', label: (r) => r.reg_no, order: 'reg_no', campusScoped: true } as RelationDef,
  driver: { table: 'drivers', label: (r) => r.full_name, order: 'full_name', campusScoped: true } as RelationDef,
  route: { table: 'routes', label: (r) => r.name, order: 'name', campusScoped: true } as RelationDef,
  grading: { table: 'grading_systems', label: (r) => r.name, order: 'name' } as RelationDef,
  expCat: { table: 'expense_categories', label: (r) => r.name, order: 'name' } as RelationDef,
};

const defs: ResourceDef[] = [
  // ───────── academics ─────────
  { key: 'campuses', table: 'campuses', title: 'Campuses', singular: 'Campus', perm: 'campuses', hub: { href: '/settings', label: 'Settings' },
    columns: [col('name', 'Name'), col('code', 'Code'), col('city', 'City', 'text', true), col('phone', 'Phone', 'text', true), col('is_active', 'Active', 'bool')],
    fields: [text('name', 'Campus name', { required: true }), text('code', 'Code', { required: true, hint: 'Short unique code, e.g. MAIN or NORTH', maxLength: 12 }), text('address', 'Address'), text('city', 'City'), text('phone', 'Phone'), { name: 'email', label: 'Email', type: 'email' }, check('is_active', 'Active', { default: true })],
    searchCols: ['name', 'code'], canDelete: false },
  { key: 'academic-years', table: 'academic_years', title: 'Academic years', singular: 'Academic year', perm: 'academics', hub: { href: '/academics', label: 'Academics' },
    columns: [col('name', 'Year'), col('start_date', 'Starts', 'date'), col('end_date', 'Ends', 'date'), col('is_current', 'Current', 'badge')],
    fields: [text('name', 'Name', { required: true, hint: 'e.g. 2026-27' }), date('start_date', 'Starts', { required: true }), date('end_date', 'Ends', { required: true })],
    order: ['start_date', false], searchCols: ['name'],
    rowRpcs: [{ label: 'Make current', fn: 'set_current_year', args: (r) => ({ p_year: r.id }), when: (r) => !r.is_current, perm: 'academics.manage', confirm: 'Make this the current academic year? New fee vouchers and attendance will use it.' }] },
  { key: 'terms', table: 'terms', title: 'Terms', singular: 'Term', perm: 'academics', hub: { href: '/academics', label: 'Academics' }, select: '*,academic_years(name)',
    columns: [col('academic_years.name', 'Year'), col('name', 'Term'), col('start_date', 'Starts', 'date'), col('end_date', 'Ends', 'date')],
    fields: [rel('academic_year_id', 'Academic year', R.year, { required: true }), text('name', 'Name', { required: true }), date('start_date', 'Starts', { required: true }), date('end_date', 'Ends', { required: true }), num('sort_order', 'Order', { default: 1 })],
    order: ['start_date', false] },
  { key: 'departments', table: 'departments', title: 'Departments', singular: 'Department', perm: 'academics', hub: { href: '/academics', label: 'Academics' },
    columns: [col('name', 'Name'), col('name_ur', 'Urdu name', 'text', true)], fields: [text('name', 'Name', { required: true }), text('name_ur', 'Name (Urdu)')], searchCols: ['name'], order: ['name', true] },
  { key: 'designations', table: 'designations', title: 'Designations', singular: 'Designation', perm: 'staff', hub: { href: '/staff', label: 'Staff' },
    columns: [col('name', 'Name')], fields: [text('name', 'Name', { required: true })], searchCols: ['name'], order: ['name', true] },
  { key: 'subjects', table: 'subjects', title: 'Subjects', singular: 'Subject', perm: 'academics', hub: { href: '/academics', label: 'Academics' }, select: '*,departments(name)',
    columns: [col('code', 'Code'), col('name', 'Subject'), col('departments.name', 'Department', 'text', true), col('is_elective', 'Elective', 'bool', true)],
    fields: [text('code', 'Code', { required: true, hint: 'e.g. MATH', maxLength: 12 }), text('name', 'Name', { required: true }), text('name_ur', 'Name (Urdu)'), rel('department_id', 'Department', R.department), check('is_elective', 'Elective subject')],
    searchCols: ['name', 'code'], order: ['name', true] },
  { key: 'houses', table: 'houses', title: 'Houses', singular: 'House', perm: 'academics', hub: { href: '/academics', label: 'Academics' },
    columns: [col('name', 'Name'), col('color', 'Colour', 'text', true)], fields: [text('name', 'Name', { required: true }), { name: 'color', label: 'Colour', type: 'color', default: '#0b6b5f' }], order: ['name', true] },
  { key: 'classes', table: 'classes', title: 'Classes', singular: 'Class', perm: 'academics', campusScoped: true, hub: { href: '/academics', label: 'Academics' }, select: '*,campuses(name)',
    columns: [col('name', 'Class'), col('level', 'Order', 'number'), col('campuses.name', 'Campus', 'text', true), col('is_active', 'Active', 'bool', true)],
    fields: [text('name', 'Class name', { required: true, hint: 'e.g. Class 5' }), num('level', 'Order', { required: true, hint: 'Used for sorting and the promotion path (1, 2, 3 …)', default: 1 }),
      rel('next_class_id', 'Promotes to', { ...R.classes, select: 'id,name,level' }, { hint: 'Next class in the promotion path' }), check('is_active', 'Active', { default: true })],
    searchCols: ['name'], order: ['level', true] },
  { key: 'sections', table: 'sections', title: 'Sections', singular: 'Section', perm: 'academics', campusScoped: true, hub: { href: '/academics', label: 'Academics' }, select: '*,classes(name,level),rooms(name)',
    columns: [col('classes.name', 'Class'), col('name', 'Section'), col('capacity', 'Capacity', 'number'), col('rooms.name', 'Room', 'text', true)],
    fields: [rel('class_id', 'Class', R.classes, { required: true, createOnly: true }), text('name', 'Section name', { required: true, hint: 'A, B, Red …', maxLength: 20 }), num('capacity', 'Capacity', { default: 35 }), rel('room_id', 'Room', R.rooms)],
    order: ['name', true] },
  { key: 'rooms', table: 'rooms', title: 'Rooms', singular: 'Room', perm: 'academics', campusScoped: true, hub: { href: '/academics', label: 'Academics' },
    columns: [col('name', 'Room'), col('kind', 'Type', 'badge'), col('capacity', 'Capacity', 'number')],
    fields: [text('name', 'Name', { required: true }), sel('kind', 'Type', ['classroom', 'lab', 'library', 'hall', 'office', 'other'], { default: 'classroom' }), num('capacity', 'Capacity')], order: ['name', true], searchCols: ['name'] },
  { key: 'periods', table: 'periods', title: 'Periods & breaks', singular: 'Period', perm: 'academics', campusScoped: true, hub: { href: '/timetable', label: 'Timetable' },
    columns: [col('sort_order', '#', 'number'), col('name', 'Period'), col('start_time', 'Start', 'time'), col('end_time', 'End', 'time'), col('is_break', 'Break', 'bool')],
    fields: [text('name', 'Name', { required: true, hint: 'Period 1, Break …' }), time('start_time', 'Starts', { required: true }), time('end_time', 'Ends', { required: true }), num('sort_order', 'Order', { default: 1 }), check('is_break', 'This is a break')],
    order: ['sort_order', true] },
  { key: 'class-subjects', table: 'class_subjects', title: 'Subjects per class', singular: 'Class subject', perm: 'academics', campusScoped: true, hub: { href: '/academics', label: 'Academics' }, select: '*,classes(name,level),subjects(name,code)',
    columns: [col('classes.name', 'Class'), col('subjects.name', 'Subject'), col('periods_per_week', 'Periods / week', 'number')],
    fields: [rel('class_id', 'Class', R.classes, { required: true, createOnly: true }), rel('subject_id', 'Subject', R.subject, { required: true, createOnly: true }), num('periods_per_week', 'Periods per week')], order: ['periods_per_week', false] },
  { key: 'teacher-assignments', table: 'teacher_assignments', title: 'Teacher assignments', singular: 'Assignment', perm: 'academics', campusScoped: true, hub: { href: '/academics', label: 'Academics' },
    select: '*,sections(name,classes(name)),subjects(name),staff(full_name),academic_years(name)',
    columns: [col('academic_years.name', 'Year', 'text', true), col('sections.classes.name', 'Class'), col('sections.name', 'Section'), col('subjects.name', 'Subject'), col('staff.full_name', 'Teacher'), col('is_class_teacher', 'Class teacher', 'bool')],
    fields: [rel('academic_year_id', 'Academic year', R.year, { required: true }), rel('section_id', 'Section', R.sections, { required: true }), rel('subject_id', 'Subject (blank for class teacher only)', R.subject), rel('staff_id', 'Teacher', R.staff, { required: true }), check('is_class_teacher', 'Class teacher of this section')],
    order: ['academic_year_id', false] },

  // ───────── fees ─────────
  { key: 'fee-categories', table: 'fee_categories', title: 'Fee categories', singular: 'Fee category', perm: 'fees', hub: { href: '/fees', label: 'Fees' },
    columns: [col('code', 'Code'), col('name', 'Name'), col('kind', 'Type', 'badge'), col('is_active', 'Active', 'bool')],
    fields: [text('code', 'Code', { required: true, maxLength: 16 }), text('name', 'Name', { required: true }), text('name_ur', 'Name (Urdu)'), sel('kind', 'Type', ['monthly', 'admission', 'annual', 'exam', 'transport', 'hostel', 'misc'], { default: 'monthly', required: true }), check('is_active', 'Active', { default: true })],
    order: ['code', true], canDelete: false },
  { key: 'fee-structures', table: 'fee_structures', title: 'Fee structure', singular: 'Fee amount', perm: 'fees', campusScoped: true, hub: { href: '/fees', label: 'Fees' },
    select: '*,classes(name,level),fee_categories(name),academic_years(name),campuses(name)',
    columns: [col('academic_years.name', 'Year', 'text', true), col('campuses.name', 'Campus', 'text', true), col('classes.name', 'Class'), col('fee_categories.name', 'Category'), col('amount', 'Amount', 'money'), col('frequency', 'Frequency', 'badge')],
    fields: [rel('academic_year_id', 'Academic year', R.year, { required: true }), rel('class_id', 'Class (blank = all classes)', R.classes), rel('fee_category_id', 'Fee category', R.category, { required: true }), money('amount', 'Amount (Rs)', { required: true }),
      sel('frequency', 'Charged', [['monthly', 'Every month'], ['once', 'Once'], ['annual', 'Yearly'], ['termly', 'Every term']], { default: 'monthly', required: true, hint: 'Only "Every month" fees go on the monthly voucher run; the others are billed with Generate vouchers → one-off.' })],
    order: ['amount', false] },
  { key: 'student-discounts', table: 'student_discounts', title: 'Discounts & scholarships', singular: 'Discount', perm: 'fees', campusScoped: true, hub: { href: '/fees', label: 'Fees' }, alsoNeeds: 'fees.approve',
    select: '*,students(full_name,student_code),fee_categories(name)',
    columns: [col('students.student_code', 'ID'), col('students.full_name', 'Student'), col('kind', 'Type', 'badge'), col('calc', 'Method', 'badge', true), col('value', 'Value', 'number'), col('fee_categories.name', 'Applies to', 'text', true), col('is_active', 'Active', 'bool')],
    fields: [{ name: 'student_id', label: 'Student ID', type: 'student', required: true, createOnly: true, hint: 'Type the student ID, e.g. STD-0001' }, sel('kind', 'Type', [['scholarship', 'Scholarship'], ['concession', 'Concession'], ['sibling', 'Sibling'], ['staff_child', 'Staff child'], ['other', 'Other']], { required: true, default: 'concession' }),
      sel('calc', 'Method', [['percent', 'Percent of fee'], ['fixed', 'Fixed amount (Rs)']], { required: true, default: 'percent' }), num('value', 'Value', { required: true, min: 0.01, step: 0.01, hint: 'Percent (1–100) or rupees' }),
      rel('fee_category_id', 'Applies to (blank = all fees)', R.category), text('reason', 'Reason', { required: true }), date('valid_from', 'Valid from'), date('valid_to', 'Valid to'), check('is_active', 'Active', { default: true })],
    order: ['created_at', false] },
  { key: 'student-fee-assignments', table: 'student_fee_assignments', title: 'Student fee overrides', singular: 'Override', perm: 'fees', campusScoped: true, hub: { href: '/fees', label: 'Fees' }, alsoNeeds: 'fees.approve',
    select: '*,students(full_name,student_code),fee_categories(name),academic_years(name)',
    columns: [col('students.student_code', 'ID'), col('students.full_name', 'Student'), col('fee_categories.name', 'Category'), col('amount_override', 'Amount', 'money'), col('is_exempt', 'Exempt', 'bool')],
    fields: [{ name: 'student_id', label: 'Student ID', type: 'student', required: true, createOnly: true }, rel('academic_year_id', 'Academic year', R.year, { required: true }), rel('fee_category_id', 'Fee category', R.category, { required: true }), money('amount_override', 'Custom amount (Rs)', { hint: 'Replaces the class fee for this student, or adds a custom recurring charge' }), check('is_exempt', 'Exempt from this fee'), text('note', 'Note')],
    order: ['amount_override', false] },

  // ───────── finance ─────────
  { key: 'accounts', table: 'accounts', title: 'Cash & bank accounts', singular: 'Account', perm: 'finance', hub: { href: '/finance', label: 'Finance' },
    columns: [col('name', 'Account'), col('kind', 'Type', 'badge'), col('methods', 'Receives', 'text', true), col('opening_balance', 'Opening balance', 'money'), col('is_active', 'Active', 'bool')],
    fields: [text('name', 'Name', { required: true }), sel('kind', 'Type', ['cash', 'bank', 'petty_cash', 'wallet'], { required: true, default: 'cash' }), text('bank_name', 'Bank'), text('account_no', 'Account no.'), money('opening_balance', 'Opening balance', { min: -1e9 }), check('is_active', 'Active', { default: true })],
    order: ['name', true] },
  { key: 'expense-categories', table: 'expense_categories', title: 'Expense categories', singular: 'Category', perm: 'finance', hub: { href: '/finance', label: 'Finance' },
    columns: [col('name', 'Name'), col('is_active', 'Active', 'bool')], fields: [text('name', 'Name', { required: true }), text('name_ur', 'Name (Urdu)'), check('is_active', 'Active', { default: true })], order: ['name', true] },
  { key: 'vendors', table: 'vendors', title: 'Vendors', singular: 'Vendor', perm: 'finance', hub: { href: '/finance', label: 'Finance' },
    columns: [col('name', 'Vendor'), col('phone', 'Phone'), col('ntn', 'NTN', 'text', true)], fields: [text('name', 'Name', { required: true }), text('phone', 'Phone'), { name: 'email', label: 'Email', type: 'email' }, text('address', 'Address'), text('ntn', 'NTN')], searchCols: ['name'], order: ['name', true] },
  { key: 'expenses', table: 'expenses', title: 'Expenses', singular: 'Expense', perm: 'finance', campusScoped: true, hub: { href: '/finance', label: 'Finance' }, alsoNeeds: 'financial.access', select: '*,expense_categories(name),vendors(name)',
    columns: [col('expense_no', 'No.'), col('expense_date', 'Date', 'date'), col('expense_categories.name', 'Category'), col('description', 'Description', 'text', true), col('amount', 'Amount', 'money'), col('status', 'Status', 'badge')],
    fields: [rel('category_id', 'Category', R.expCat), rel('vendor_id', 'Vendor', { table: 'vendors', label: (r) => r.name, order: 'name' }), money('amount', 'Amount (Rs)', { required: true, min: 1 }), date('expense_date', 'Date', { required: true }), text('description', 'Description', { required: true })],
    order: ['expense_date', false], searchCols: ['description', 'expense_no'],
    rowRpcs: [
      { label: 'Approve', fn: 'decide_expense', args: (r) => ({ p_id: r.id, p_decision: 'approved' }), when: (r) => r.status === 'pending', perm: 'finance.approve', tone: 'primary' },
      { label: 'Reject', fn: 'decide_expense', args: (r) => ({ p_id: r.id, p_decision: 'rejected' }), when: (r) => r.status === 'pending', perm: 'finance.approve', tone: 'danger', confirm: 'Reject this expense?' },
      { label: 'Mark paid', fn: 'pay_expense', args: (r) => ({ p_id: r.id, p_account: null }), when: (r) => r.status === 'approved', perm: 'finance.edit', tone: 'primary', confirm: 'Pay this expense from the default cash account?' },
    ] },
  { key: 'gl-accounts', table: 'gl_accounts', title: 'Chart of accounts', singular: 'GL account', perm: 'finance', hub: { href: '/finance', label: 'Finance' }, alsoNeeds: 'financial.access',
    columns: [col('code', 'Code'), col('name', 'Name'), col('type', 'Type', 'badge'), col('is_active', 'Active', 'bool')],
    fields: [text('code', 'Code', { required: true, maxLength: 12 }), text('name', 'Name', { required: true }), sel('type', 'Type', ['asset', 'liability', 'equity', 'income', 'expense'], { required: true }), check('is_active', 'Active', { default: true })], order: ['code', true] },

  // ───────── HR ─────────
  { key: 'leave-types', table: 'leave_types', title: 'Leave types', singular: 'Leave type', perm: 'leave', hub: { href: '/leave', label: 'Leave' },
    columns: [col('name', 'Leave type'), col('days_per_year', 'Days / year', 'number'), col('is_paid', 'Paid', 'bool')],
    fields: [text('name', 'Name', { required: true }), text('name_ur', 'Name (Urdu)'), num('days_per_year', 'Days per year', { step: 0.5, required: true }), check('is_paid', 'Paid leave', { default: true })], order: ['name', true] },
  { key: 'salary-structures', table: 'salary_structures', title: 'Salary structures', singular: 'Salary structure', perm: 'payroll', campusScoped: true, hub: { href: '/payroll', label: 'Payroll' }, alsoNeeds: 'financial.access', select: '*,staff(full_name,employee_code)',
    columns: [col('staff.employee_code', 'ID'), col('staff.full_name', 'Staff'), col('effective_from', 'From', 'date'), col('basic_salary', 'Basic', 'money'), col('tax_percent', 'Tax %', 'number', true)],
    fields: [{ name: 'staff_id', label: 'Employee ID', type: 'staff', required: true, createOnly: true, hint: 'e.g. EMP-0001' }, date('effective_from', 'Effective from', { required: true }), money('basic_salary', 'Basic salary', { required: true }), money('house_allowance', 'House allowance', { default: 0 }), money('medical_allowance', 'Medical allowance', { default: 0 }),
      money('conveyance_allowance', 'Conveyance', { default: 0 }), money('other_allowance', 'Other allowance', { default: 0 }), num('tax_percent', 'Tax (% of gross)', { max: 100, step: 0.1, default: 0 }), money('other_deduction', 'Fixed monthly deduction', { default: 0 }), money('overtime_rate_per_hour', 'Overtime rate per hour', { hint: 'Leave blank to derive from basic salary' }), text('notes', 'Notes')],
    order: ['effective_from', false] },
  { key: 'staff-loans', table: 'staff_loans', title: 'Staff loans', singular: 'Loan', perm: 'payroll', campusScoped: true, hub: { href: '/payroll', label: 'Payroll' }, alsoNeeds: 'financial.access', select: '*,staff(full_name,employee_code)',
    columns: [col('staff.full_name', 'Staff'), col('amount', 'Amount', 'money'), col('monthly_installment', 'Instalment', 'money'), col('remaining', 'Remaining', 'money'), col('status', 'Status', 'badge')],
    fields: [{ name: 'staff_id', label: 'Employee ID', type: 'staff', required: true, createOnly: true }, money('amount', 'Loan amount', { required: true, min: 1 }), money('monthly_installment', 'Monthly instalment', { required: true, min: 1 }), money('remaining', 'Remaining', { required: true, hint: 'Same as the amount for a new loan' }), date('issued_on', 'Issued on', { required: true })],
    order: ['issued_on', false] },
  { key: 'payroll-adjustments', table: 'payroll_adjustments', title: 'Bonuses & deductions', singular: 'Adjustment', perm: 'payroll', campusScoped: true, hub: { href: '/payroll', label: 'Payroll' }, alsoNeeds: 'financial.access', select: '*,staff(full_name,employee_code)',
    columns: [col('month', 'Month', 'date'), col('staff.full_name', 'Staff'), col('kind', 'Type', 'badge'), col('label', 'Label'), col('amount', 'Amount', 'money')],
    fields: [{ name: 'staff_id', label: 'Employee ID', type: 'staff', required: true, createOnly: true }, date('month', 'Month (first day)', { required: true, hint: 'e.g. 2026-09-01' }), sel('kind', 'Type', ['bonus', 'deduction'], { required: true }), text('label', 'Label', { required: true }), money('amount', 'Amount', { required: true, min: 1 })],
    order: ['month', false] },

  // ───────── operations ─────────
  { key: 'library-books', table: 'library_books', title: 'Books', singular: 'Book', perm: 'library', campusScoped: true, hub: { href: '/library', label: 'Library' },
    columns: [col('title', 'Title'), col('author', 'Author', 'text', true), col('category', 'Category', 'text', true), col('quantity', 'Copies', 'number'), col('available', 'Available', 'number'), col('shelf', 'Shelf', 'text', true)],
    fields: [text('title', 'Title', { required: true }), text('author', 'Author'), text('isbn', 'ISBN'), text('category', 'Category'), text('publisher', 'Publisher'), num('quantity', 'Copies', { required: true, default: 1 }), num('available', 'Available now', { required: true, default: 1 }), text('shelf', 'Shelf')],
    searchCols: ['title', 'author', 'isbn'], order: ['title', true] },
  { key: 'vehicles', table: 'vehicles', title: 'Vehicles', singular: 'Vehicle', perm: 'transport', campusScoped: true, hub: { href: '/transport', label: 'Transport' },
    columns: [col('reg_no', 'Registration'), col('make_model', 'Model'), col('capacity', 'Seats', 'number'), col('fitness_expiry', 'Fitness expiry', 'date', true), col('insurance_expiry', 'Insurance expiry', 'date', true), col('is_active', 'Active', 'bool')],
    fields: [text('reg_no', 'Registration no.', { required: true }), text('make_model', 'Make / model'), num('capacity', 'Seats', { required: true, default: 30, min: 1 }), date('fitness_expiry', 'Fitness expiry'), date('insurance_expiry', 'Insurance expiry'), text('gps_device_id', 'GPS device id', { hint: 'For future live tracking integration' }), check('is_active', 'Active', { default: true })], searchCols: ['reg_no'], order: ['reg_no', true] },
  { key: 'drivers', table: 'drivers', title: 'Drivers', singular: 'Driver', perm: 'transport', campusScoped: true, hub: { href: '/transport', label: 'Transport' },
    columns: [col('full_name', 'Driver'), col('phone', 'Phone'), col('license_no', 'Licence'), col('license_expiry', 'Licence expiry', 'date', true), col('is_active', 'Active', 'bool')],
    fields: [text('full_name', 'Full name', { required: true }), { name: 'phone', label: 'Phone', type: 'tel' }, text('cnic', 'CNIC'), text('license_no', 'Licence no.'), date('license_expiry', 'Licence expiry'), check('is_active', 'Active', { default: true })], searchCols: ['full_name'], order: ['full_name', true] },
  { key: 'routes', table: 'routes', title: 'Routes', singular: 'Route', perm: 'transport', campusScoped: true, hub: { href: '/transport', label: 'Transport' }, select: '*,vehicles(reg_no),drivers(full_name)',
    columns: [col('name', 'Route'), col('vehicles.reg_no', 'Vehicle'), col('drivers.full_name', 'Driver'), col('monthly_fee', 'Monthly fee', 'money'), col('start_time', 'Departs', 'time', true), col('is_active', 'Active', 'bool')],
    fields: [text('name', 'Route name', { required: true }), rel('vehicle_id', 'Vehicle', R.vehicle), rel('driver_id', 'Driver', R.driver), money('monthly_fee', 'Monthly fee (Rs)', { default: 0 }), time('start_time', 'Departs at'), check('is_active', 'Active', { default: true })], order: ['name', true] },
  { key: 'route-stops', table: 'route_stops', title: 'Route stops', singular: 'Stop', perm: 'transport', campusScoped: true, hub: { href: '/transport', label: 'Transport' }, select: '*,routes(name)',
    columns: [col('routes.name', 'Route'), col('stop_order', '#', 'number'), col('name', 'Stop'), col('pickup_time', 'Pickup', 'time'), col('drop_time', 'Drop', 'time', true)],
    fields: [rel('route_id', 'Route', R.route, { required: true, createOnly: true }), text('name', 'Stop name', { required: true }), num('stop_order', 'Order', { required: true, default: 1, min: 1 }), time('pickup_time', 'Pickup time'), time('drop_time', 'Drop time'), num('lat', 'Latitude', { min: -90, max: 90, step: 0.000001 }), num('lng', 'Longitude', { min: -180, max: 180, step: 0.000001 })], order: ['stop_order', true] },
  { key: 'student-transport', table: 'student_transport', title: 'Student transport', singular: 'Assignment', perm: 'transport', campusScoped: true, hub: { href: '/transport', label: 'Transport' }, select: '*,students(full_name,student_code),routes(name),route_stops!student_transport_pickup_stop_id_campus_id_fkey(name)',
    columns: [col('students.student_code', 'ID'), col('students.full_name', 'Student'), col('routes.name', 'Route'), col('monthly_fee', 'Fee', 'money'), col('is_active', 'Active', 'bool')],
    fields: [{ name: 'student_id', label: 'Student ID', type: 'student', required: true, createOnly: true }, rel('route_id', 'Route', R.route, { required: true, createOnly: true }), rel('pickup_stop_id', 'Pickup stop', { table: 'route_stops', label: (r) => r.name, order: 'name', campusScoped: true }), rel('drop_stop_id', 'Drop stop', { table: 'route_stops', label: (r) => r.name, order: 'name', campusScoped: true }), money('monthly_fee', 'Monthly fee (Rs)', { default: 0, hint: 'Added to the monthly voucher automatically' }), date('start_date', 'Starts', { required: true }), date('end_date', 'Ends'), check('is_active', 'Active', { default: true })],
    order: ['start_date', false] },
  { key: 'hostel-buildings', table: 'hostel_buildings', title: 'Hostel buildings', singular: 'Building', perm: 'hostel', campusScoped: true, hub: { href: '/hostel', label: 'Hostel' },
    columns: [col('name', 'Building'), col('gender', 'For', 'badge')], fields: [text('name', 'Name', { required: true }), sel('gender', 'For', [['male', 'Boys'], ['female', 'Girls'], ['mixed', 'Mixed']])], order: ['name', true] },
  { key: 'hostel-rooms', table: 'hostel_rooms', title: 'Hostel rooms', singular: 'Room', perm: 'hostel', campusScoped: true, hub: { href: '/hostel', label: 'Hostel' }, select: '*,hostel_buildings(name)',
    columns: [col('hostel_buildings.name', 'Building'), col('room_no', 'Room'), col('floor', 'Floor', 'number'), col('capacity', 'Beds', 'number')],
    fields: [rel('building_id', 'Building', { table: 'hostel_buildings', label: (r) => r.name, order: 'name', campusScoped: true }, { required: true, createOnly: true }), text('room_no', 'Room no.', { required: true }), num('floor', 'Floor', { default: 0 }), num('capacity', 'Beds', { required: true, default: 4, min: 1 })], order: ['room_no', true] },
  { key: 'hostel-allocations', table: 'hostel_allocations', title: 'Hostel allocations', singular: 'Allocation', perm: 'hostel', campusScoped: true, hub: { href: '/hostel', label: 'Hostel' }, select: '*,students(full_name,student_code),hostel_rooms(room_no)',
    columns: [col('students.student_code', 'ID'), col('students.full_name', 'Student'), col('hostel_rooms.room_no', 'Room'), col('bed_no', 'Bed', 'number'), col('monthly_fee', 'Fee', 'money'), col('status', 'Status', 'badge')],
    fields: [{ name: 'student_id', label: 'Student ID', type: 'student', required: true, createOnly: true }, rel('room_id', 'Room', { table: 'hostel_rooms', label: (r) => `Room ${r.room_no}`, order: 'room_no', campusScoped: true }, { required: true, createOnly: true }), num('bed_no', 'Bed no.', { required: true, min: 1, default: 1 }), money('monthly_fee', 'Monthly fee (Rs)', { default: 0 }), date('from_date', 'From', { required: true }), sel('status', 'Status', ['active', 'vacated'], { default: 'active', required: true })], order: ['from_date', false] },
  { key: 'hostel-visitors', table: 'hostel_visitors', title: 'Hostel visitors', singular: 'Visitor', perm: 'hostel', campusScoped: true, hub: { href: '/hostel', label: 'Hostel' }, select: '*,students(full_name)',
    columns: [col('in_time', 'In', 'datetime'), col('students.full_name', 'Student'), col('visitor_name', 'Visitor'), col('relation', 'Relation', 'text', true), col('out_time', 'Out', 'datetime', true)],
    fields: [{ name: 'student_id', label: 'Student ID', type: 'student', required: true, createOnly: true }, text('visitor_name', 'Visitor name', { required: true }), text('relation', 'Relation'), text('cnic', 'CNIC'), text('purpose', 'Purpose')], order: ['in_time', false] },
  { key: 'calendar-events', table: 'calendar_events', title: 'Calendar events', singular: 'Event', perm: 'calendar', hub: { href: '/calendar', label: 'Calendar' },
    columns: [col('start_date', 'Date', 'date'), col('title', 'Event'), col('kind', 'Type', 'badge'), col('is_public', 'On website', 'bool', true)],
    fields: [text('title', 'Title', { required: true }), sel('kind', 'Type', [['holiday', 'Holiday'], ['exam', 'Exam'], ['event', 'Event'], ['meeting', 'Meeting'], ['ptm', 'Parent–teacher meeting'], ['admission', 'Admission date']], { required: true, default: 'event' }), date('start_date', 'Date', { required: true }), date('end_date', 'Ends (multi-day)'), time('start_time', 'Starts'), time('end_time', 'Ends'), area('description', 'Details'), check('is_public', 'Show on public website')],
    order: ['start_date', false], searchCols: ['title'], insertDefaults: {} },
  { key: 'announcements', table: 'announcements', title: 'Announcements', singular: 'Announcement', perm: 'announcements', hub: { href: '/announcements', label: 'Announcements' },
    columns: [col('publish_at', 'Published', 'datetime'), col('title', 'Title'), col('audience', 'Audience', 'badge'), col('level', 'Level', 'badge', true), col('is_pinned', 'Pinned', 'bool', true)],
    fields: [text('title', 'Title', { required: true }), area('body', 'Message', { required: true, maxLength: 2000 }), sel('audience', 'Audience', [['all', 'Everyone'], ['parents', 'Parents'], ['students', 'Students'], ['teachers', 'Teachers'], ['staff', 'Staff']], { default: 'all', required: true }), sel('level', 'Level', ['info', 'success', 'warning', 'urgent'], { default: 'info', required: true }), check('is_pinned', 'Pin to top')],
    order: ['publish_at', false], searchCols: ['title'] },

  // ───────── exams ─────────
  { key: 'grading-systems', table: 'grading_systems', title: 'Grading systems', singular: 'Grading system', perm: 'exams', hub: { href: '/exams', label: 'Exams' },
    columns: [col('name', 'Name'), col('kind', 'Type', 'badge'), col('pass_percentage', 'Pass %', 'number'), col('is_default', 'Default', 'bool')],
    fields: [text('name', 'Name', { required: true }), sel('kind', 'Type', [['grade', 'Letter grades'], ['gpa', 'GPA'], ['percentage', 'Percentage only']], { required: true, default: 'grade' }), num('pass_percentage', 'Pass percentage', { required: true, max: 100, default: 40, step: 0.5 }), check('use_gpa', 'Calculate GPA'), check('is_default', 'Default for new exams')], canDelete: false },
  { key: 'grade-bands', table: 'grade_bands', title: 'Grade bands', singular: 'Grade band', perm: 'exams', hub: { href: '/exams', label: 'Exams' }, select: '*,grading_systems(name)',
    columns: [col('grading_systems.name', 'System'), col('grade', 'Grade'), col('min_percent', 'From %', 'number'), col('max_percent', 'To %', 'number'), col('gpa_points', 'GPA', 'number'), col('description', 'Remark', 'text', true), col('is_pass', 'Pass', 'bool')],
    fields: [rel('grading_system_id', 'Grading system', R.grading, { required: true, createOnly: true }), text('grade', 'Grade', { required: true, maxLength: 6 }), num('min_percent', 'From %', { required: true, max: 100, step: 0.01 }), num('max_percent', 'To %', { required: true, max: 100, step: 0.01 }), num('gpa_points', 'GPA points', { step: 0.01, max: 10 }), text('description', 'Description'), check('is_pass', 'Counts as pass', { default: true })],
    order: ['min_percent', false] },

  // ───────── communication & CMS ─────────
  { key: 'notification-templates', table: 'notification_templates', title: 'Message templates', singular: 'Template', perm: 'communication', hub: { href: '/communication', label: 'Communication' },
    columns: [col('key', 'Event'), col('channel', 'Channel', 'badge'), col('language', 'Language', 'badge'), col('is_active', 'Active', 'bool')],
    fields: [sel('key', 'Event', ['fee_reminder', 'fee_receipt', 'absence_alert', 'result_published', 'admission_confirmation', 'homework', 'announcement', 'event_reminder'], { required: true, createOnly: true }), sel('channel', 'Channel', [['whatsapp', 'WhatsApp'], ['sms', 'SMS'], ['email', 'Email'], ['in_app', 'In-app'], ['push', 'Push']], { required: true, createOnly: true }), sel('language', 'Language', [['en', 'English'], ['ur', 'اردو']], { required: true, createOnly: true }),
      text('subject', 'Subject (email)'), area('body', 'Message', { required: true, maxLength: 1000, hint: 'Placeholders: {{student_name}} {{class_name}} {{amount}} {{due_date}} {{month}} {{receipt_no}} {{date}} {{exam_name}} {{percentage}} {{grade}} {{title}} {{message}} {{school_name}}' }), text('provider_template', 'WhatsApp approved template name', { hint: 'Meta requires pre-approved templates for business-initiated messages' }), check('is_active', 'Active', { default: true })],
    order: ['key', true] },
  { key: 'cms-notices', table: 'cms_notices', title: 'Website notices', singular: 'Notice', perm: 'cms', hub: { href: '/website', label: 'Website' },
    columns: [col('published_at', 'Published', 'datetime'), col('title', 'Title'), col('is_published', 'Live', 'bool')], fields: [text('title', 'Title', { required: true }), area('body', 'Text'), check('is_published', 'Published', { default: true })], order: ['published_at', false] },
  { key: 'cms-teachers', table: 'cms_teachers', title: 'Website: faculty', singular: 'Faculty member', perm: 'cms', hub: { href: '/website', label: 'Website' },
    columns: [col('name', 'Name'), col('designation', 'Designation'), col('is_published', 'Live', 'bool')], fields: [text('name', 'Name', { required: true }), text('designation', 'Designation'), area('bio', 'Short bio'), num('sort_order', 'Order', { default: 0 }), check('is_published', 'Published', { default: true })], order: ['sort_order', true] },
];

export const RESOURCES: Record<string, ResourceDef> = Object.fromEntries(defs.map((d) => [d.key, d]));
export const getResource = (key: string) => RESOURCES[key];
